name: gh-page

on: push

permissions: write-all

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: |
          bun install
          pip install mdpo

      - name: Update po and doc
        run: |
          cd docs \
          && bash ./helper.sh --md2po \
          && bash ./helper.sh --po2md

      - name: Build
        run: |
          cd docs && bun run docs:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/.vitepress/dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
